# Generated by Django 5.1.6 on 2025-03-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes_comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
