# Generated by Django 5.1.6 on 2025-04-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profile",
            new_name="user",
        ),
    ]
